language: node_js

node_js:
 - 4
 - 6
 - 7

env:
  - BABEL_ENV=development

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

before_script:
  - npm prune

after_success:
  - BABEL_ENV=v4 npm run compile -- -d lib/node4
  - BABEL_ENV=v6 npm run compile -- -d lib/node6
  - BABEL_ENV=v7 npm run compile -- -d lib/node7
  - BABEL_ENV=browser npm run compile -- -d lib/browser

before_deploy:
  - npm install semantic-release
  - npm install codeclimate-test-reporter
  - npm run coverage -- --coverage-report=text-lcov | codeclimate-test-reporter

deploy:
  skip_cleanup: true
  provider: script
  script: semantic-release pre && npm publish && semantic-release post

  on:
    branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - /^greenkeeper\/.+/
