language: node_js

matrix:
  include:
    - node: "4.x"
      env: BABEL_ENV=node4
      os: linux

    - node: "4.x"
      env: BABEL_ENV=node4
      os: osx

    - node: "5.x"
      env: BABEL_ENV=node5
      os: linux

    - node: "5.x"
      env: BABEL_ENV=node5
      os: osx

    - node: "6.x"
      env: BABEL_ENV=node6
      os: linux

    - node: "6.x"
      env: BABEL_ENV=node6
      os: osx

    - node: "7.x"
      env: BABEL_ENV=node7
      os: linux

    - node: "7.x"
      env: BABEL_ENV=node7
      os: osx

cache:
  directories:
    - node_modules

after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back) > /dev/null
  - npm run coverage
  - npm run codeclimate
  - BABEL_ENV=node4 npm run compile -- -d lib
  - BABEL_ENV=node5 npm run compile -- -d lib/node5
  - BABEL_ENV=node6 npm run compile -- -d lib/node6
  - BABEL_ENV=node7 npm run compile -- -d lib/node7
  - BABEL_ENV=browsers npm run compile -- -d lib/browsers
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
    - "/^greenkeeper-.+/"
